<a href="https://colab.research.google.com/github/DuanMingbai/PyTorch_Tutorials_cn/blob/main/Introduction%20to%20PyTorch/2_%E5%BC%A0%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#张量

张量（tensor）是一种很特殊的数据类型，它和数组、矩阵非常像，在使用PyTorch的时候，我们在一个模型中用tensor来为输入和输出编码，包括模型当中的参数

tensor和Numpy's的ndarrays很像，除此之外，tensor可以运行在GPU或者其他硬件加速器上。事实上tensor和Numpy的array通常可以享用相同的底层内存，所以说不需要取复制数据（详情见[Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）。如果你对ndarrays很熟悉的话，你使用tensorAPI将会如有神助，如果不熟悉，那咱们就开始吧！

In [ ]:
import torch
import numpy as np

##初始化一个tensor

tensor能够被各种方式初始化，让我们来看如下几个方式

###直接干数据

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

###通过Numpy的array

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

###通过其他的tensor

新tensor保留参数tensor的属性（维度，数据类型），除了完全覆盖

In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

###通过任意的常量

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5954, 0.0105, 0.4852],
        [0.6647, 0.5206, 0.2294]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##Tensor的属性

Tensor的属性描述了它的维度，数据类型和这个家伙存储在哪个设备上

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


##Tensor的操作

tensor的操作超过一百多种，包括算法，线性代数，矩阵操作（转置，切片，索引），采样，更多完整的描述点击[链接文字](https://pytorch.org/docs/stable/torch.html)。

这些操作都可以被运行在GPU上，如果你用Colab，通过修改运行时类型，来获取GPU。

tensor默认是被创建在CPU上的。我们可以准确度地移动tensor到GPU上用```.to```方法（当然了，必须保证你的GPU可用），但是要记住，在复制特别大的tensor到GPU的时候，会耗费大量的时间和存储。

In [ ]:
#我们将tensor移动到可用的GPU上
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

True


我们尝试一些列表当中的操作，如果你熟悉Numpy中的API，那么你会发现使用tensor就像过马路一样简单。

**标准的类似Numpy索引和切片**

In [ ]:
tensor=torch.ones(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
tensor[:, 1]=0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**组合tensor**，你可以使用```torch.cat```根据给定维度去连接一系列的tensor，另请参阅[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)

In [ ]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**算法操作**

In [ ]:
#下面的代码计算了连个tensor的乘法，y1,y2,y3会有相同的结果
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


#下面代码计算每一个元素的乘积，z1,z2,z3会有相同值
z1 = tensor * tensor
z1 = tensor.mul(tensor)

z3=torch.rand_like(tensor)
torch.mul(tensor, tensor,out=z3)
#译者理解，这两个的区别应该是，第一个是标准的矩阵乘法（行x列然后相加），第二个是将简单的将每个元素乘起来

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**单元素tensor**如果你有一个单元素tensor，例如将tensor所有值聚合为一个值，你可以通过```item()```将这个tensor转换成Python的数值

In [ ]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(12.)
12.0 <class 'float'>


**自动赋值操作**将结果存储在操作数中的操作被称作自动赋值操作。他们用```_```后缀表示，例如：```x.copy_(y)```，```x.t_()```，会更改```x```。

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


Note

自动赋值操作节省了一些内存，但是在计算导数的时候会报错因为会立刻丢掉历史记录。所以，不推荐使用这个方法。

##与Numpy桥接

CPU 和 NumPy 数组上的张量可以共享它们的底层内存位置，改变一个也会改变另一个。

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n=t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


###Tensor to NumPy array

在tensor上做出改变的时候映射在Numpy array

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n： {n}")

t: tensor([2., 2., 2., 2., 2.])
n： [2. 2. 2. 2. 2.]


###Numpy array转换tensor

In [ ]:
n=np.ones(5)
t=torch.from_numpy(n)

在array上做出改变会映射到tensor中

In [ ]:
np.add(n,1,out=n)
print(f"t: {t}")
print(f"n:{n}")

t: tensor([4., 4., 4., 4., 4.])
n:[4. 4. 4. 4. 4.]
